----GET INSTANCE INFO
SELECT SERVERNAME = CONVERT(NVARCHAR(128),SERVERPROPERTY('SERVERNAME'))  
,LOCAL_NET_ADDRESS AS 'IPADDRESS' 
--, NETBIOS = CONVERT(NVARCHAR(128),SERVERPROPERTY('COMPUTERNAMEPHYSICALNETBIOS'))  
, EDITION = CONVERT(NVARCHAR(128),SERVERPROPERTY('EDITION'))  
, VERSION = (select @@version)
, PRODUCTVERSION = CONVERT(NVARCHAR(128),SERVERPROPERTY('PRODUCTVERSION'))  
, COLLATION = CONVERT(NVARCHAR(128),SERVERPROPERTY('COLLATION'))  
, [MAXDOP] = (SELECT VALUE_IN_USE FROM SYS.CONFIGURATIONS WHERE NAME='MAX DEGREE OF PARALLELISM')   
, SQLMEMORY = (SELECT VALUE_IN_USE FROM SYS.CONFIGURATIONS WHERE NAME='MAX SERVER MEMORY (MB)')  
, ISCLUSTERED = CONVERT(BIT,SERVERPROPERTY('ISCLUSTERED'))  
, ISFULLTEXTINSTALLED = CONVERT(BIT,SERVERPROPERTY('ISFULLTEXTINSTALLED'))  
, ISINTEGRATEDSECURITYONLY = CONVERT(BIT,SERVERPROPERTY('ISINTEGRATEDSECURITYONLY'))  
, FILESTREAMCONFIGUREDLEVEL = CONVERT(TINYINT,SERVERPROPERTY('FILESTREAMCONFIGUREDLEVEL'))  
, FILESTREAMEFFECTIVELEVEL = CONVERT(TINYINT,SERVERPROPERTY('FILESTREAMEFFECTIVELEVEL'))  
, SQLSORTORDERNAME = CONVERT(NVARCHAR(128),SERVERPROPERTY('SQLSORTORDERNAME')) 
 FROM SYS.DM_EXEC_CONNECTIONS WHERE SESSION_ID = @@SPID ORDER BY PRODUCTVERSION DESC
 -----------------------------------------------